name: replit-subdomain-connector
region: nyc
services:
  - name: api
    github:
      repo: maxdevs97/replit-subdomain-connector
      branch: main
      deploy_on_push: true
    source_dir: /server
    run_command: node server.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DO_API_TOKEN
        value: ${DO_API_TOKEN}
        type: SECRET
      - key: PORT
        value: "8080"
    http_port: 8080
    routes:
      - path: /api
  - name: web
    github:
      repo: maxdevs97/replit-subdomain-connector
      branch: main
      deploy_on_push: true
    source_dir: /client
    build_command: npm install && npm run build
    run_command: npx serve -s build -l $PORT
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: REACT_APP_API_URL
        value: ${api.PUBLIC_URL}
    http_port: 3000
    routes:
      - path: /
